# Generated by Django 3.2.10 on 2021-12-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestPolymorphic', '0002_auto_20211210_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other',
            options={},
        ),
    ]
