# Generated by Django 3.2.10 on 2021-12-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestPolymorphic', '0003_alter_other_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherChild',
            fields=[
                ('other_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TestPolymorphic.other')),
                ('texi', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('TestPolymorphic.other',),
        ),
    ]
